// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import EnterSubmitController from "./enter_submit_controller"
application.register("enter-submit", EnterSubmitController)
