require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/EmptyMethod:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Metrics/BlockLength:
  Max: 50

RSpec/MultipleMemoizedHelpers:
  Enabled: false
