default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: diary_analyzer_ai_development
  primary_replica:
    <<: *default
    database: diary_analyzer_ai_development
    replica: true

test:
  primary:
    <<: *default
    database: diary_analyzer_ai_test
  primary_replica:
    <<: *default
    database: diary_analyzer_ai_test
    replica: true

production:
  primary:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: diary_analyzer_ai_production
    username: diary_analyzer_ai
  primary_replica:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: diary_analyzer_ai_production
    username: diary_analyzer_ai
    replica: true
