default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: diary_analyzer_ai_development
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
  primary_replica:
    <<: *default
    database: diary_analyzer_ai_development
    username: <%= ENV['REPLICA_DATABASE_USERNAME'] %>
    password: <%= ENV['REPLICA_DATABASE_PASSWORD'] %>
    host: <%= ENV['REPLICA_DATABASE_HOST'] %>
    replica: true

test:
  primary:
    <<: *default
    database: diary_analyzer_ai_test
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
  primary_replica:
    <<: *default
    database: diary_analyzer_ai_test
    username: <%= ENV['REPLICA_DATABASE_USERNAME'] %>
    password: <%= ENV['REPLICA_DATABASE_PASSWORD'] %>
    host: <%= ENV['REPLICA_DATABASE_HOST'] %>
    replica: true

production:
  primary:
    <<: *default
    database: diary_analyzer_ai_production
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
  primary_replica:
    <<: *default
    database: diary_analyzer_ai_production
    username: <%= ENV['REPLICA_DATABASE_USERNAME'] %>
    password: <%= ENV['REPLICA_DATABASE_PASSWORD'] %>
    host: <%= ENV['REPLICA_DATABASE_HOST'] %>
    replica: true